from typing import Protocol


class RecordType(Protocol):
    def create_initial_data(self) -> dict[str, object]: ...

    def validate(self, payload: dict[str, object]) -> None: ...

    def serialize(self, data: dict[str, object]) -> dict[str, object]: ...

    def deserialize(self, payload: dict[str, object]) -> dict[str, object]: ...

    def render(self, payload: dict[str, object]) -> str: ...

    def preview(self, payload: dict[str, object]) -> str: ...

    def build_editor_steps(self) -> tuple[object, ...]: ...
